### ISSUE TITLE
{DOCS} Especificação das tecnologias e ferramentas que utilizaremos

### ISSUE THREAD

**Issue by titosilva** [titosilva/askme#2]
# O que deve ser feito?
Para entrega até o dia 11/04/2021, é necessário criar um documento com a especificação do que utilizaremos. Além disso, precisaremos adicionar as historietas de usuário, mas o documento gerado por essa issue servirá como base. Portanto, não é necessário, ainda, criar as historietas, mas apenas criar um documento compartilhável, como Google Docs por exemplo, e preencher com as informações sobre tecnologias que vamos usar e ferramentas:

- React.js
- Node.js com Express.js
- MongoDB com Mongoose
- JTest
- Github Projects como Kanban
- Github como ferramenta de versionamento
- Outras tecnologias que talvez não estejam nessa lista

# Qual a prioridade? Lembre de adicionar labels conforme a prioridade.
Alta

**Comment by Tiagosf00** [comment]
Link das especificações no [Google Docs.](https://docs.google.com/document/d/1KsFmlCZJJEMTlN-oJFWm6cweWRDNF9YIcCtvaDunwug/edit?usp=sharing)
:dog2:
